name: ludo_server
description: Authoritative Ludo game server.
publish_to: none
environment:
  sdk: ^3.5.0
resolution: workspace

dependencies:
  ludo_engine:
    path: ../ludo_engine
  shelf: ^1.4.0
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.0
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.25.0
