"""Ludo RNG store graphics, v2.

Why v2: v1 (assets/store/, generated by tool/store_graphics.py) renders four
flat colour quadrants -- red/green/blue/yellow -- separated by a cross. Its own
README argues at length that this is not the well known four-square corporate
mark; the pixels disagree. At icon size the structure it relies on (thin lane
outlines, small safe-square rings) disappears and what is left is a 2x2 grid of
flat colour in that exact palette.

v2 drops the grid entirely and draws the thing the product is actually about:
the die. The four seat colours survive as the pips, so the Ludo palette is
still present without the layout that causes the resemblance.

Everything is drawn at 4x and downsampled with Lanczos, so edges anti-alias and
output is deterministic.
"""
from PIL import Image, ImageDraw, ImageFont

S = 4  # supersample

# Palette: the app's own Material 3 purple (seed colour of the running client)
# plus the four seat colours from packages/ludo_client/lib/src/board.dart.
BG_TOP    = (0x4A, 0x39, 0x8C)
BG_BOTTOM = (0x2A, 0x1F, 0x54)
DIE       = (0xFA, 0xF7, 0xF0)
DIE_EDGE  = (0x1B, 0x14, 0x38)
SEAT = [(0xD3, 0x2F, 0x2F), (0x38, 0x8E, 0x3C), (0xFB, 0xC0, 0x2D), (0x19, 0x76, 0xD2)]
WORD      = (0xFA, 0xF7, 0xF0)
SUB       = (0xC9, 0xBE, 0xEA)

FONT_BOLD = "/usr/share/fonts/truetype/google-fonts/Poppins-Bold.ttf"
FONT_MED  = "/usr/share/fonts/truetype/google-fonts/Poppins-Medium.ttf"


def vertical_gradient(w, h):
    img = Image.new("RGB", (w, h), BG_TOP)
    d = ImageDraw.Draw(img)
    for y in range(h):
        t = y / max(h - 1, 1)
        d.line(
            [(0, y), (w, y)],
            fill=tuple(round(a + (b - a) * t) for a, b in zip(BG_TOP, BG_BOTTOM)),
        )
    return img


def draw_die(img, cx, cy, size, corner_frac=0.22, rot=-8):
    """A white rounded-square die with four coloured pips, drawn on its own
    transparent layer so it can be rotated without touching the ground."""
    pad = int(size * 0.35)
    layer = Image.new("RGBA", (size + 2 * pad, size + 2 * pad), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    x0, y0 = pad, pad
    x1, y1 = pad + size, pad + size
    r = int(size * corner_frac)
    edge = max(2, int(size * 0.035))
    d.rounded_rectangle([x0, y0, x1, y1], radius=r, fill=DIE, outline=DIE_EDGE, width=edge)

    # four pips, one per seat colour, on the diagonals of a 4-face
    pip_r = int(size * 0.105)
    off = int(size * 0.24)
    mx, my = (x0 + x1) // 2, (y0 + y1) // 2
    spots = [(mx - off, my - off), (mx + off, my - off),
             (mx - off, my + off), (mx + off, my + off)]
    # red top-left, green top-right, yellow bottom-left, blue bottom-right
    order = [0, 1, 2, 3]
    for (px, py), i in zip(spots, order):
        d.ellipse([px - pip_r, py - pip_r, px + pip_r, py + pip_r],
                  fill=SEAT[i], outline=DIE_EDGE, width=max(1, edge // 2))

    layer = layer.rotate(rot, resample=Image.BICUBIC, expand=False)
    img.paste(layer, (cx - layer.width // 2, cy - layer.height // 2), layer)


def make_icon(path, out=512):
    w = h = out * S
    img = vertical_gradient(w, h)
    draw_die(img, w // 2, h // 2, int(w * 0.62))
    img.resize((out, out), Image.LANCZOS).save(path)
    return path


def make_feature(path, w=1024, h=500):
    W, H = w * S, h * S
    img = vertical_gradient(W, H)
    draw_die(img, int(W * 0.20), H // 2, int(H * 0.62))

    d = ImageDraw.Draw(img)
    title = ImageFont.truetype(FONT_BOLD, int(H * 0.19))
    sub = ImageFont.truetype(FONT_MED, int(H * 0.062))
    tx = int(W * 0.37)
    right_limit = W - int(W * 0.045)
    lines = ["Private rooms, played with friends.",
             "Every dice roll can be checked."]
    d.text((tx, int(H * 0.36)), "Ludo RNG", font=title, fill=WORD, anchor="lm")
    d.text((tx, int(H * 0.585)), lines[0], font=sub, fill=SUB, anchor="lm")
    d.text((tx, int(H * 0.695)), lines[1], font=sub, fill=SUB, anchor="lm")

    # A store banner whose text runs off the right edge is the failure this
    # check exists to make impossible: assert every line fits before saving.
    for text, font in [("Ludo RNG", title)] + [(l, sub) for l in lines]:
        end = tx + d.textlength(text, font=font)
        if end > right_limit:
            raise SystemExit(
                f"line {text!r} ends at {end}, past the {right_limit} margin")
    img.resize((w, h), Image.LANCZOS).save(path)
    return path


if __name__ == "__main__":
    import os
    out = os.path.dirname(os.path.abspath(__file__))
    print(make_icon(os.path.join(out, "icon-512.png")))
    print(make_feature(os.path.join(out, "feature-1024x500.png")))
    # the size that decides whether anyone taps it
    Image.open(os.path.join(out, "icon-512.png")).resize((48, 48), Image.LANCZOS).save(
        os.path.join(out, "icon-48-check.png"))
