/// Room code shape, duplicated from the server's own alphabet because this
/// client cannot depend on the server package.
///
/// Copied from docs/PROTOCOL.md section 2, "Identity and the two secrets":
/// 6 characters from `ABCDEFGHJKLMNPQRSTUVWXYZ23456789` (32 symbols). `0`,
/// `O`, `1` and `I` are excluded. `L` is kept deliberately: with `1` gone
/// there is nothing left for it to be confused with, and dropping it would
/// leave 31 symbols. Do not "fix" this list to also drop `L`; a room code
/// generated by the server can and will contain one.
///
/// This duplication is contained by test/room_code_alphabet_test.dart, which
/// asserts this constant against the documented alphabet. If docs/PROTOCOL.md
/// section 2 ever changes, that test and this constant change together.
const String roomCodeAlphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

/// The fixed length of a room code.
const int roomCodeLength = 6;

/// Upper-cases a raw room code and strips spaces and dashes, so a code
/// dictated over a phone call and typed back with a dash still validates.
String normalizeRoomCode(String raw) {
  return raw.toUpperCase().replaceAll(RegExp(r'[\s-]'), '');
}

/// True if [code] is a syntactically valid room code: exactly
/// [roomCodeLength] characters, every one of them from [roomCodeAlphabet].
///
/// This is a local shape check only. It says nothing about whether a room
/// with this code exists, is full, or has expired; only the server knows
/// that.
bool isValidRoomCode(String code) {
  if (code.length != roomCodeLength) {
    return false;
  }
  for (final char in code.split('')) {
    if (!roomCodeAlphabet.contains(char)) {
      return false;
    }
  }
  return true;
}
