// Replays the golden corpus described in work order 003: one JSON object
// per line, each recording a complete run of intentions against a seed and
// the exact stateHash and seq that run must produce.
//
// The corpus file is generated by tool/generate_corpus.dart and blessed by
// the master after the engine is reviewed; it is deliberately absent from
// this worker's tree. A missing or empty corpus file must fail loudly and
// name the path, never pass by iterating over zero records.
//
// Ambiguity worth flagging for whoever blesses the corpus: the work order's
// example intention objects carry only {"t", "seat", "token"?}, with no
// documented field for an intention that is expected to be rejected. The
// only existing generator, tool/generate_corpus.dart, never records a
// rejected intention at all (it treats any Rejected result as a fixture
// bug and throws). This replayer follows that: every intention is expected
// to be Applied unless it carries an optional "error" field naming an
// EngineError by its Dart identifier (e.g. "illegalMove"), which is
// supported for forward compatibility but not exercised by anything that
// currently generates this file.

import 'dart:convert';
import 'dart:io';

import 'package:ludo_engine/ludo_engine.dart';
import 'package:test/test.dart';

const String _corpusPath = 'test/golden/corpus.jsonl';

EngineError _parseEngineError(String name) {
  for (final value in EngineError.values) {
    if (value.name == name) {
      return value;
    }
  }
  throw FormatException('unknown EngineError "$name" in golden corpus');
}

GameConfig _parseConfig(Map<String, Object?> record) {
  final rawSeats = record['seats']! as List<Object?>;
  final seats = rawSeats.map((s) => s! as int).toList();
  final rawRules = record['rules']! as Map<String, Object?>;
  final rules = RulesConfig(
    blocks: rawRules['blocks']! as bool,
    captureBonus: rawRules['captureBonus']! as bool,
  );
  final seed = record['seed']! as int;
  return GameConfig(seats: seats, rules: rules, seed: seed);
}

Intention _parseIntention(Map<String, Object?> raw) {
  final type = raw['t']! as String;
  final seat = raw['seat']! as int;
  switch (type) {
    case 'roll':
      return RollIntention(seat);
    case 'move':
      return MoveIntention(seat, raw['token']! as int);
    default:
      throw FormatException('unknown intention type "$type" in golden corpus');
  }
}

void _replayRecord(Map<String, Object?> record) {
  final name = record['name']! as String;
  final seed = record['seed']! as int;
  final config = _parseConfig(record);
  final rawIntentions = record['intentions']! as List<Object?>;
  final finalHash = record['finalHash']! as String;
  final finalSeq = record['finalSeq']! as int;

  var state = newGame(config);
  for (var i = 0; i < rawIntentions.length; i++) {
    final raw = rawIntentions[i]! as Map<String, Object?>;
    final intention = _parseIntention(raw);
    final result = apply(state, intention);
    final expectedErrorName = raw['error'] as String?;

    if (expectedErrorName != null) {
      expect(
        result,
        isA<Rejected>(),
        reason: 'game "$name" (seed=$seed), intention $i ($raw): expected '
            'a rejection but got $result',
      );
      expect(
        (result as Rejected).error,
        _parseEngineError(expectedErrorName),
        reason: 'game "$name" (seed=$seed), intention $i ($raw)',
      );
      // A rejected intention does not advance state, per
      // docs/ENGINE_API.md section 4.
      continue;
    }

    expect(
      result,
      isA<Applied>(),
      reason: 'game "$name" (seed=$seed), intention $i ($raw) was rejected: '
          '${result is Rejected ? result.error : result}',
    );
    state = (result as Applied).state;
  }

  expect(
    stateHash(state),
    finalHash,
    reason: 'game "$name" (seed=$seed): final stateHash does not match the '
        'pinned golden value after replaying ${rawIntentions.length} '
        'intentions',
  );
  expect(
    state.seq,
    finalSeq,
    reason: 'game "$name" (seed=$seed): final seq does not match the '
        'pinned golden value after replaying ${rawIntentions.length} '
        'intentions',
  );
}

void main() {
  final file = File(_corpusPath);

  if (!file.existsSync()) {
    test('golden corpus file exists', () {
      fail(
        'golden corpus file not found at "${file.absolute.path}". It is '
        'generated by tool/generate_corpus.dart and blessed by the master '
        'after the engine is reviewed; it does not ship with this test '
        'suite. Generate it, then re-run this test. This failure is '
        'expected and correct until that file exists; it must never be '
        'treated as a pass or a skip.',
      );
    });
    return;
  }

  final lines =
      file.readAsLinesSync().where((line) => line.trim().isNotEmpty).toList();

  test('golden corpus file is not empty', () {
    expect(
      lines,
      isNotEmpty,
      reason: 'golden corpus file "${file.absolute.path}" exists but has '
          'zero records. A replay of zero games must not report a pass.',
    );
  });

  for (var lineNumber = 0; lineNumber < lines.length; lineNumber++) {
    final record = jsonDecode(lines[lineNumber]) as Map<String, Object?>;
    final name = record['name'] as String? ?? 'line ${lineNumber + 1}';
    final seed = record['seed'];
    test('golden corpus: $name (seed=$seed)', () {
      _replayRecord(record);
    });
  }
}
