// Replays the golden corpus described in work order 003 and updated by
// docs/ENGINE_API.md section 7: one JSON object per line, each recording a
// complete run of intentions against a seed and the exact stateHash and seq
// that run must produce.
//
// The corpus file is generated by tool/generate_corpus.dart and blessed by
// the master after the engine is reviewed. This replayer owns reading it,
// not producing it: a missing or empty corpus file must fail loudly and
// name the path, never pass by iterating over zero records.
//
// docs/ENGINE_API.md section 7 makes "face" mandatory on every "roll"
// record: "A replayer that treats a missing face as anything other than a
// hard failure would silently accept a corpus from before this change and
// prove nothing; it must name the record and fail." That is what
// _parseIntention below does -- no default, no skip, no zero -- and it
// names both the record and the physical line number in the corpus file,
// because "line 17" is what someone actually greps for.
//
// Ambiguity worth flagging for whoever blesses the corpus: the work order's
// example intention objects carry only {"t", "seat", "token"?, "face"?},
// with no documented field for an intention that is expected to be
// rejected. The only existing generator, tool/generate_corpus.dart, never
// records a rejected intention at all (it treats any Rejected result as a
// fixture bug and throws). This replayer follows that: every intention is
// expected to be Applied unless it carries an optional "error" field naming
// an EngineError by its Dart identifier (e.g. "illegalMove"), which is
// supported for forward compatibility but not exercised by anything that
// currently generates this file.

import 'dart:convert';
import 'dart:io';

import 'package:ludo_engine/ludo_engine.dart';
import 'package:test/test.dart';

const String _corpusPath = 'test/golden/corpus.jsonl';

EngineError _parseEngineError(String name) {
  for (final value in EngineError.values) {
    if (value.name == name) {
      return value;
    }
  }
  throw FormatException('unknown EngineError "$name" in golden corpus');
}

GameConfig _parseConfig(Map<String, Object?> record) {
  final rawSeats = record['seats']! as List<Object?>;
  final seats = rawSeats.map((s) => s! as int).toList();
  final rawRules = record['rules']! as Map<String, Object?>;
  final rules = RulesConfig(
    blocks: rawRules['blocks']! as bool,
    captureBonus: rawRules['captureBonus']! as bool,
  );
  final seed = record['seed']! as int;
  return GameConfig(seats: seats, rules: rules, seed: seed);
}

/// Builds the [Intention] for one record of a corpus record's `intentions`
/// list. [recordName] and [physicalLine] (1-based, the line in
/// [_corpusPath] the whole record came from) and [intentionIndex] (0-based,
/// the position of [raw] within that record's `intentions` array) exist so
/// that any failure here names exactly where in the file to look.
Intention _parseIntention(
  Map<String, Object?> raw, {
  required String recordName,
  required int physicalLine,
  required int intentionIndex,
}) {
  final type = raw['t']! as String;
  final seat = raw['seat']! as int;
  switch (type) {
    case 'roll':
      final rawFace = raw['face'];
      if (rawFace is! int) {
        throw FormatException(
          'golden corpus line $physicalLine, record "$recordName", '
          'intention $intentionIndex ($raw): a "roll" record has no '
          'integer "face" field. docs/ENGINE_API.md section 7 makes '
          '"face" mandatory on every roll record now that the engine '
          'draws no randomness of its own (rule 38); a corpus recorded '
          'before that change is not valid input to this replayer and '
          'must be regenerated by tool/generate_corpus.dart. Refusing to '
          'default it to anything, including 0.',
        );
      }
      return RollIntention(seat, rawFace);
    case 'move':
      return MoveIntention(seat, raw['token']! as int);
    default:
      throw FormatException(
        'golden corpus line $physicalLine, record "$recordName", '
        'intention $intentionIndex ($raw): unknown intention type "$type"',
      );
  }
}

void _replayRecord(Map<String, Object?> record, int physicalLine) {
  final name = record['name']! as String;
  final seed = record['seed']! as int;
  final config = _parseConfig(record);
  final rawIntentions = record['intentions']! as List<Object?>;
  final finalHash = record['finalHash']! as String;
  final finalSeq = record['finalSeq']! as int;

  var state = newGame(config);
  for (var i = 0; i < rawIntentions.length; i++) {
    final raw = rawIntentions[i]! as Map<String, Object?>;
    final intention = _parseIntention(
      raw,
      recordName: name,
      physicalLine: physicalLine,
      intentionIndex: i,
    );
    final result = apply(state, intention);
    final expectedErrorName = raw['error'] as String?;

    if (expectedErrorName != null) {
      expect(
        result,
        isA<Rejected>(),
        reason: 'game "$name" (seed=$seed, line $physicalLine), intention '
            '$i ($raw): expected a rejection but got $result',
      );
      expect(
        (result as Rejected).error,
        _parseEngineError(expectedErrorName),
        reason: 'game "$name" (seed=$seed, line $physicalLine), intention '
            '$i ($raw)',
      );
      // A rejected intention does not advance state, per
      // docs/ENGINE_API.md section 4.
      continue;
    }

    expect(
      result,
      isA<Applied>(),
      reason: 'game "$name" (seed=$seed, line $physicalLine), intention $i '
          '($raw) was rejected: '
          '${result is Rejected ? result.error : result}',
    );
    state = (result as Applied).state;
  }

  expect(
    stateHash(state),
    finalHash,
    reason: 'game "$name" (seed=$seed, line $physicalLine): final '
        'stateHash does not match the pinned golden value after replaying '
        '${rawIntentions.length} intentions',
  );
  expect(
    state.seq,
    finalSeq,
    reason: 'game "$name" (seed=$seed, line $physicalLine): final seq does '
        'not match the pinned golden value after replaying '
        '${rawIntentions.length} intentions',
  );
}

void main() {
  final file = File(_corpusPath);

  if (!file.existsSync()) {
    test('golden corpus file exists', () {
      fail(
        'golden corpus file not found at "${file.absolute.path}". It is '
        'generated by tool/generate_corpus.dart and blessed by the master '
        'after the engine is reviewed; it does not ship with this test '
        'suite. Generate it, then re-run this test. This failure is '
        'expected and correct until that file exists; it must never be '
        'treated as a pass or a skip.',
      );
    });
    return;
  }

  final rawLines = file.readAsLinesSync();
  // (physical, 1-based line number; record text), skipping blank lines,
  // keeping the physical line number even when blank lines are skipped so
  // every failure names a real line in the file.
  final entries = <(int physicalLine, String content)>[
    for (var i = 0; i < rawLines.length; i++)
      if (rawLines[i].trim().isNotEmpty) (i + 1, rawLines[i]),
  ];

  test('golden corpus file is not empty', () {
    expect(
      entries,
      isNotEmpty,
      reason: 'golden corpus file "${file.absolute.path}" exists but has '
          'zero records. A replay of zero games must not report a pass.',
    );
  });

  for (final (physicalLine, content) in entries) {
    final record = jsonDecode(content) as Map<String, Object?>;
    final name = record['name'] as String? ?? 'line $physicalLine';
    final seed = record['seed'];
    test('golden corpus: $name (seed=$seed, line $physicalLine)', () {
      _replayRecord(record, physicalLine);
    });
  }
}
