// Checks the implementation against packages/fair_dice/test/vectors.json,
// the frozen, cross-checked oracle for this scheme (see FAIRNESS.md 2.4).
// vectors.json is the only source of truth read here: every expected value
// below comes from parsing that file, never from a literal copied out of it
// by hand, so the file can be regenerated by whoever owns it without this
// test needing to change.
//
// Each vector gets its own named test() so a failure names the vector that
// broke, rather than one test looping over all of them and reporting only
// "some assertion failed".

import 'dart:convert';
import 'dart:io';

import 'package:fair_dice/fair_dice.dart';
import 'package:test/test.dart';

void main() {
  final raw = File('test/vectors.json').readAsStringSync();
  final vectors = jsonDecode(raw) as Map<String, dynamic>;

  final serverSecretHex = vectors['server_secret'] as String;
  final chainLength = vectors['chain_length'] as int;
  final gameId = vectors['game_id'] as String;
  final clientSeeds = vectors['client_seeds'] as String;
  final expectedCommit = vectors['chain_commit'] as String;

  final chain = DiceChain.build(
    hexDecode(serverSecretHex),
    chainLength: chainLength,
  );

  test('chain_commit derived from server_secret with chain_length $chainLength',
      () {
    expect(chain.commit, equals(expectedCommit));
  });

  test(
      'deriveChainLink(server_secret, chain_length, 0) agrees with DiceChain.build',
      () {
    // The same value, computed the other way: hashing backward from the
    // secret without ever materialising the array, per the doc comment on
    // deriveChainLink.
    expect(
      hexEncode(deriveChainLink(hexDecode(serverSecretHex), chainLength, 0)),
      equals(expectedCommit),
    );
  });

  final rolls =
      (vectors['rolls'] as List<dynamic>).cast<Map<String, dynamic>>();
  for (final vector in rolls) {
    final k = vector['k'] as int;
    final expectedReveal = vector['reveal'] as String;
    final expectedParent = vector['parent'] as String;
    final expectedDie = vector['die'] as int;
    final expectedWordsRejected = vector['words_rejected'] as int;

    test('rolls[k=$k]: chain link matches reveal', () {
      expect(chain.reveal(k), equals(expectedReveal));
    });

    test('rolls[k=$k]: reveal hashes to its recorded parent', () {
      expect(
        verifyReveal(reveal: expectedReveal, parent: expectedParent),
        isTrue,
        reason: 'SHA-256(s[$k]) should equal s[${k - 1}]',
      );
    });

    test('rolls[k=$k]: parent is the chain link immediately before it', () {
      expect(chain.reveal(k - 1), equals(expectedParent));
    });

    test('rolls[k=$k]: HMAC draw produces the recorded die', () {
      final draw = drawDieDetailed(expectedReveal, gameId, clientSeeds, k, 0);
      expect(draw.face, equals(expectedDie));
    });

    test('rolls[k=$k]: HMAC draw rejects the recorded number of words', () {
      final draw = drawDieDetailed(expectedReveal, gameId, clientSeeds, k, 0);
      expect(draw.wordsRejected, equals(expectedWordsRejected));
    });

    test(
        'rolls[k=$k]: drawDie (face-only entry point) agrees with drawDieDetailed',
        () {
      expect(
        drawDie(expectedReveal, gameId, clientSeeds, k, 0),
        equals(expectedDie),
      );
    });
  }

  final backgammonRolls = (vectors['backgammon_rolls'] as List<dynamic>)
      .cast<Map<String, dynamic>>();
  for (final vector in backgammonRolls) {
    final k = vector['k'] as int;
    final reveal = vector['reveal'] as String;
    final dice = (vector['dice'] as List<dynamic>).cast<int>();

    test('backgammon_rolls[k=$k]: die 0 of two from one reveal', () {
      expect(drawDie(reveal, gameId, clientSeeds, k, 0), equals(dice[0]));
    });

    test('backgammon_rolls[k=$k]: die 1 of two from one reveal', () {
      expect(drawDie(reveal, gameId, clientSeeds, k, 1), equals(dice[1]));
    });

    test('backgammon_rolls[k=$k]: reveal for the shared roll matches the chain',
        () {
      expect(chain.reveal(k), equals(reveal));
    });
  }

  // The two rejection-sampling vectors above are both words_rejected: 0, so
  // this loop also asserts that vectors.json is not silently missing the
  // field on any roll entry: if a future regeneration of vectors.json ever
  // records a nonzero rejection count, the per-roll test above already
  // covers it without any change here.
  test('every rolls[] vector records words_rejected explicitly', () {
    for (final vector in rolls) {
      expect(vector.containsKey('words_rejected'), isTrue,
          reason: 'rolls[k=${vector['k']}] is missing words_rejected');
    }
  });

  group('properties not tied to a single vectors.json entry', () {
    test('hexDecode(hexEncode(bytes)) is the identity', () {
      final bytes = List<int>.generate(32, (i) => (i * 37 + 5) % 256);
      expect(hexDecode(hexEncode(bytes)), equals(bytes));
    });

    test('verifyReveal rejects a reveal that does not hash to the given parent',
        () {
      final someReveal = rolls.first['reveal'] as String;
      expect(
        verifyReveal(reveal: someReveal, parent: 'ff' * 32),
        isFalse,
      );
    });

    test('verifyReveal is case-insensitive on parent', () {
      final k = rolls.first['k'] as int;
      final reveal = rolls.first['reveal'] as String;
      final parent = rolls.first['parent'] as String;
      expect(k, greaterThan(0));
      expect(
        verifyReveal(reveal: reveal, parent: parent.toUpperCase()),
        isTrue,
      );
    });

    test('drawDie is deterministic: same inputs, same face, every call', () {
      final reveal = rolls.first['reveal'] as String;
      final k = rolls.first['k'] as int;
      final first = drawDie(reveal, gameId, clientSeeds, k, 0);
      for (var i = 0; i < 5; i++) {
        expect(drawDie(reveal, gameId, clientSeeds, k, 0), equals(first));
      }
    });
  });
}
